FROM ubuntu:18.04
RUN /bin/bash -c "apt-get update && \apt-get install -y \
                  build-essential python3 python3-pip virtualenv python3-dev \
                   libssl-dev libffi-dev libcurl4-openssl-dev zip python3-venv python-dev "

VOLUME ["/ansible/"]
